language: java

sudo: false

jdk:
  - openjdk7
  - oraclejdk7

script:
  - cd coursework1_implementation
  - mvn install -DskipTests=true
  - mvn test
  - ./ex1_run_frequency_analysis
  - ./ex1_run_cipher_analysis
  - ./ex1_run_rotation_decipher

notifications:
  email:
    on_success: change
    on_failure: change
