language: java

sudo: false

jdk:
  - openjdk7
  - oraclejdk7

script:
  - cd coursework1
  - mvn install -DskipTests=true
  - mvn test

notifications:
  email:
    on_success: change
    on_failure: change
