language: java

sudo: false

jdk:
  - openjdk7
  - oraclejdk7

script:
  - cd coursework1_implementation
  - mvn install -DskipTests=true -q
  - mvn test
  - ./ex1_run_frequency_analysis
  - ./ex1_run_cipher_analysis
  - ./ex1_run_rotation_decipher
  # - ./ex2_run_cipher_decipher_cycle
  - ./ex2_compare_ciphertext_frequencies

notifications:
  email:
    on_success: change
    on_failure: change
