language: java

sudo: false

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  # - oraclejdk8

script:
  - cd coursework1_implementation
  - mvn install -DskipTests=true -q
  - mvn test
  - ./ex1_run_frequency_analysis
  - ./ex1_run_cipher_analysis
  - ./ex1_run_rotation_decipher
  # - ./ex2_run_cipher_decipher_cycle
  - ./ex2_encrypt_newcastleuniversity
  - ./ex2_compare_ciphertext_frequencies
  - ./ex2_decipher_set_ciphertext
  - ./ex2_ciphertext_analysis
  - ./ex3_generate_pad
  - ./ex3_encrypt_decrypt_cycle
  - ./ex3_cryptanalysis

notifications:
  email:
    on_success: change
    on_failure: change
