package com.dan_nixon.csc3621.cw1.ex3;

import org.junit.*;
import static org.junit.Assert.*;
import java.util.Map;
import com.dan_nixon.csc3621.cw1.ex3.OneTimePadGenerator;

public class OneTimePadGeneratorTest
{
  @Test
  public void testPadGeneratorIntSeed()
  {
    int seed = 0x0F1E2D3C;
    byte[] pad = OneTimePadGenerator.generateOneTimePad(seed, 10);

    assertEquals(10, pad.length);

    // Generated from seed
    assertEquals((byte) 0x0F, pad[0]);
    assertEquals((byte) 0x1E, pad[1]);
    assertEquals((byte) 0x2D, pad[2]);
    assertEquals((byte) 0x3C, pad[3]);

    // Generated by iteration
    assertEquals((byte) 0x11, pad[4]);
  }

  @Test
  public void testPadGeneratorTimeSeed()
  {
    byte[] pad = OneTimePadGenerator.generateOneTimePad(10);

    assertEquals(10, pad.length);
  }
}
