#!/bin/bash

JAVA_FLAGS="-cp target/*.jar"
CLASS=com.dan_nixon.csc3621.cw2.ex3.DiffieHellmanAttackApp

TRANSCRIPT_FILE=dhke_attack_trans.txt

java $JAVA_FLAGS $CLASS $TRANSCRIPT_FILE

cat $TRANSCRIPT_FILE

# rm $TRANSCRIPT_FILE
