#!/bin/bash

JAVA_FLAGS="-cp target/*.jar"
CLASS=com.dan_nixon.csc3621.cw1.ex1.Analysis

CIPHER_FILE=src/test/resources/Exercise1Ciphertext.txt
PLAIN_FILE=src/test/resources/pg1661.txt

java $JAVA_FLAGS $CLASS --cipher-file $CIPHER_FILE $PLAIN_FILE
