#!/bin/bash

JAVA_FLAGS="-cp target/*.jar"
CLASS=com.dan_nixon.csc3621.cw1.ex2.VigenereApp

KEY=ncl

PLAIN_FILE=src/test/resources/pg1661.txt
TEMP_CIPHER_FILE=cipher.txt

java $JAVA_FLAGS $CLASS --encrypt --key $KEY --file $PLAIN_FILE > $TEMP_CIPHER_FILE

echo "CIPHER TEXT:"
cat $TEMP_CIPHER_FILE

echo
echo "DECIPHERED PLAIN TEXT:"
java $JAVA_FLAGS $CLASS --decrypt --key $KEY --file $TEMP_CIPHER_FILE

rm $TEMP_CIPHER_FILE
