#!/bin/bash

JAVA_FLAGS="-cp target/*.jar"
CLASS=com.dan_nixon.csc3621.cw1.ex2.VigenereApp

KEY=plato
CIPHER_FILE=src/test/resources/Exercise2Ciphertext.txt

echo "DECIPHERED PLAIN TEXT:"
java $JAVA_FLAGS $CLASS --decrypt --key $KEY --file $CIPHER_FILE
