#!/bin/bash

KEY=ncl

PLAIN_FILE=src/test/resources/pg1661.txt
TEMP_CIPHER_FILE=cipher.txt

java -cp target/*.jar com.dan_nixon.csc3621.coursework1.ex2.VigenereApp --encrypt --key $KEY --file $PLAIN_FILE > $TEMP_CIPHER_FILE

echo "CIPHER TEXT:"
cat $TEMP_CIPHER_FILE

echo
echo "DECIPHERED PLAIN TEXT:"
java -cp target/*.jar com.dan_nixon.csc3621.coursework1.ex2.VigenereApp --decrypt --key $KEY --file $TEMP_CIPHER_FILE

rm $TEMP_CIPHER_FILE
