#!/bin/bash

PLAINTEXT=src/test/resources/Exercise1Plaintext.txt
PLAINTEXT_SAMPLE=src/test/resources/pg1661.txt

VIGENERE_KEY=ncl
VIGENERE_CIPHERTEXT=cipher.txt
SHIFT_CIPHERTEXT=src/test/resources/Exercise1Ciphertext.txt

# Run Vigenere cipher on plaintext
java -cp target/*.jar com.dan_nixon.csc3621.coursework1.ex2.VigenereApp --encrypt --key $VIGENERE_KEY --file $PLAINTEXT > $VIGENERE_CIPHERTEXT

# Run frequency count on sample plain text
echo "Plain text (sample):"
java -cp target/*.jar com.dan_nixon.csc3621.coursework1.ex1.Analysis frequency $PLAINTEXT_SAMPLE

# Run frequency count on plain text (that was ciphered)
echo
echo "Plain text (ciphered):"
java -cp target/*.jar com.dan_nixon.csc3621.coursework1.ex1.Analysis frequency $PLAINTEXT

# Run frequency count on shift cipher
echo
echo "Shift cipher:"
java -cp target/*.jar com.dan_nixon.csc3621.coursework1.ex1.Analysis frequency $SHIFT_CIPHERTEXT

# Run frequency count on Vigenere cipher
echo
echo "Vigenere cipher:"
java -cp target/*.jar com.dan_nixon.csc3621.coursework1.ex1.Analysis frequency $VIGENERE_CIPHERTEXT

rm $VIGENERE_CIPHERTEXT
