#!/bin/bash

JAVA_FLAGS="-cp target/*.jar"
CLASS=com.dan_nixon.csc3621.cw1.ex3.OneTimePadApp

PAD_FILE=src/test/resources/ex3_cw_pad.bin
CIPHER_FILE=src/test/resources/ex3_cw_cipher_target.bin

# Generate pad
java $JAVA_FLAGS $CLASS --decrypt --pad-file $PAD_FILE --cipher-file $CIPHER_FILE
